network:
  renderer: networkd
  ethernets:
    enp0s1:
      dhcp4: false
      addresses:
        - 192.168.64.10/24
      gateway4: 192.168.64.1
      nameservers:
          addresses: [127.0.0.53]
  version: 2
